[build]
command = "npm install --legacy-peer-deps"
functions = "netlify/functions"
publish = "."

[functions]
node_bundler = "esbuild"
external_node_modules = ["@sparticuz/chromium"]

Redirect rule for Single-Page Application (SPA) routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200