[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["chrome-aws-lambda", "puppeteer-core"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"