name: Update WSE Token Daily

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest
    
    steps:
    - name: Update Token via Netlify Function
      env:
        TOKEN_SECRET: ${{ secrets.UPDATE_TOKEN_SECRET }}
      run: |
        echo "Starting token update..."
        
        response=$(curl -X POST \
          -H "Authorization: Bearer ${TOKEN_SECRET}" \
          -H "Content-Type: application/json" \
          -d '{"trigger": "github-action"}' \
          https://wse-tracker.netlify.app/.netlify/functions/updateToken \
          -s -w "\nHTTP_CODE:%{http_code}")
        
        body=$(echo "$response" | sed -n '1,/^HTTP_CODE:/p' | sed '$d')
        http_code=$(echo "$response" | grep "HTTP_CODE:" | cut -d: -f2)
        
        echo "Response: $body"
        echo "Status Code: $http_code"
        
        if [ "$http_code" = "200" ]; then
          echo "Token updated successfully"
        else
          echo "Token update failed"
          echo "Debug: Token was ${#TOKEN_SECRET} characters long"
          exit 1
        fi