name: Update WSE Token

on:
  schedule:
    # كل 12 ساعة - 11:30 صباحاً و 11:30 مساءً بتوقيت السعودية
    - cron: '30 8,20 * * *'
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Setup Chrome and ChromeDriver
      run: |
        # Install Chrome
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # Install ChromeDriver
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+' | head -1)
        echo "Chrome version: $CHROME_VERSION"
        
        wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_VERSION.0.6778.69/linux64/chromedriver-linux64.zip"
        unzip -q chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        
        # Verify installations
        google-chrome --version
        chromedriver --version
    
    - name: Install Python dependencies
      run: |
        pip install selenium==4.15.2
        pip install firebase-admin==6.1.0
    
    - name: Extract and save token
      env:
        WSE_USERNAME: ${{ secrets.WSE_USERNAME }}
        WSE_PASSWORD: ${{ secrets.WSE_PASSWORD }}
        FIREBASE_CREDS: ${{ secrets.FIREBASE_CREDS }}
      run: |
        python .github/scripts/extract_token.py