name: Update WSE Token

on:
  schedule:
    - cron: '30 8,20 * * *'
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Chrome and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        pip install selenium==4.15.2 firebase-admin==6.1.0
    
    - name: Extract token
      env:
        WSE_USERNAME: ${{ secrets.WSE_USERNAME }}
        WSE_PASSWORD: ${{ secrets.WSE_PASSWORD }}
        FIREBASE_CREDS: ${{ secrets.FIREBASE_CREDS }}
      run: python .github/scripts/extract_token.py