name: Update WSE Token Daily

on:
  schedule:
    - cron: '0 */10 * * *'  # كل 10 ساعات
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install selenium webdriver-manager
        pip install firebase-admin
    
    - name: Extract and save token
      env:
        WSE_USERNAME: ${{ secrets.WSE_USERNAME }}
        WSE_PASSWORD: ${{ secrets.WSE_PASSWORD }}
        FIREBASE_CREDS: ${{ secrets.FIREBASE_CREDS }}
      run: |
        python .github/scripts/extract_token.py